---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
      git_repo_url: https://github.com/ExelleR/tikal_web_app.git
      repo_path: ./
      repo_branch: main
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
       update_cache: yes
    - name: Ansible shell module multiple commands
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install reqired packages
      apt:
         name:
         - git
         - curl
         - wget
         - nodejs
         